### ISSUE TITLE
Using background-image: radial-gradient

### ISSUE THREAD

**Issue by fabiensauce** [LeaVerou/css-variables#1]
Hi, 
I am sorry to use the 'issues' section to ask my question, but I didn't know where was the most appropriate to ask a question about your presentation from DotJs (which was great btw ;) )

How did you use the var(--mouse-x) & var(--mouse-y) into:
#mouse.slide {
	background-image: radial-gradient(
		at 50% 20%,
		white, black);
		content: "hello";
}

Another question, it is possible to concatenate a variable with string, for example:
.myClass{ margin: var(--margin-block)px; }

Thank you in advance for your help!!
Fabien

**Comment by LeaVerou** [comment]
1. `calc(100% * var(--mouse-x))`
2. You cannot concatenate yet, but you can use `calc()` like so: `calc(1px * var(--margin-block))`.
Note that you cannot go from a length (e.g. 10px) to a number, but you can go from a number to a length as shown above, so you should always prefer to have pure numbers as variables instead of CSS values.
